export const locations = [
  { value: "new-york", label: "New York", airport: "JFK" },
  { value: "los-angeles", label: "Los Angeles", airport: "LAX" },
  { value: "chicago", label: "Chicago", airport: "ORD" },
  { value: "dallas", label: "Dallas", airport: "DFW" },
  { value: "denver", label: "Denver", airport: "DEN" },
  { value: "san-francisco", label: "San Francisco", airport: "SFO" },
  { value: "seattle", label: "Seattle", airport: "SEA" },
  { value: "las-vegas", label: "Las Vegas", airport: "LAS" },
  { value: "miami", label: "Miami", airport: "MIA" },
  { value: "atlanta", label: "Atlanta", airport: "ATL" },
  { value: "boston", label: "Boston", airport: "BOS" },
  { value: "philadelphia", label: "Philadelphia", airport: "PHL" },
  { value: "phoenix", label: "Phoenix", airport: "PHX" },
  { value: "orlando", label: "Orlando", airport: "MCO" },
  { value: "houston", label: "Houston", airport: "IAH" },
  { value: "minneapolis", label: "Minneapolis", airport: "MSP" },
  { value: "detroit", label: "Detroit", airport: "DTW" },
  { value: "salt-lake-city", label: "Salt Lake City", airport: "SLC" },
  { value: "san-diego", label: "San Diego", airport: "SAN" },
  { value: "portland", label: "Portland", airport: "PDX" },
  { value: "honolulu", label: "Honolulu", airport: "HNL" },
  { value: "anchorage", label: "Anchorage", airport: "ANC" },
  { value: "nashville", label: "Nashville", airport: "BNA" },
  { value: "austin", label: "Austin", airport: "AUS" },
  { value: "new-orleans", label: "New Orleans", airport: "MSY" },
  { value: "raleigh", label: "Raleigh", airport: "RDU" },
  { value: "kansas-city", label: "Kansas City", airport: "MCI" },
  { value: "st-louis", label: "St. Louis", airport: "STL" },
  { value: "tampa", label: "Tampa", airport: "TPA" },
  { value: "charlotte", label: "Charlotte", airport: "CLT" },
  { value: "pittsburgh", label: "Pittsburgh", airport: "PIT" },
  { value: "cincinnati", label: "Cincinnati", airport: "CVG" },
  { value: "cleveland", label: "Cleveland", airport: "CLE" },
  { value: "indianapolis", label: "Indianapolis", airport: "IND" },
  { value: "columbus", label: "Columbus", airport: "CMH" },
  { value: "san-jose", label: "San Jose", airport: "SJC" },
  { value: "sacramento", label: "Sacramento", airport: "SMF" },
  { value: "milwaukee", label: "Milwaukee", airport: "MKE" },
  { value: "oklahoma-city", label: "Oklahoma City", airport: "OKC" },
  { value: "memphis", label: "Memphis", airport: "MEM" },
  { value: "louisville", label: "Louisville", airport: "SDF" },
  { value: "richmond", label: "Richmond", airport: "RIC" },
  { value: "hartford", label: "Hartford", airport: "BDL" },
  { value: "buffalo", label: "Buffalo", airport: "BUF" },
  { value: "albany", label: "Albany", airport: "ALB" },
  { value: "providence", label: "Providence", airport: "PVD" },
  { value: "jacksonville", label: "Jacksonville", airport: "JAX" },
  { value: "fort-lauderdale", label: "Fort Lauderdale", airport: "FLL" },
  { value: "west-palm-beach", label: "West Palm Beach", airport: "PBI" },
  { value: "sarasota", label: "Sarasota", airport: "SRQ" },
];
